parameters:
#    unisimon_principal.example.class: Unisimon\PrincipalBundle\Example

services:
#    unisimon_principal.example:
#        class: %unisimon_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
